package: add dhcpcd to /etc/group to fix build fail
error log:
File: '/source/yocto/build/../poky/meta/lib/rootfspostcommands.py', lineno: 26, function: sort_file
     0022:            name = entries[0]
     0023:            if mapping is None:
     0024:                id = int(entries[2])
     0025:            else:
*** 0026:                id = mapping[name]
     0027:            new_mapping[name] = id
     0028:        # Sort by numeric id first, with entire line as secondary key
     0029:        # (just in case that there is more than one entry for the same id).
     0030:        lines.sort(key=lambda line: (new_mapping[line.split(b':')[0]], line))
Exception: KeyError: b'dhcpcd'

Change-Id: I4f3c573d2a87c17c39d6f82741cf8f3ddd7bc57b
Signed-off-by: yi-hsin_hung <yi-hsin_hung@asus.com>